FROM python:3.9.13
COPY ./requirements.txt /deploy/
COPY ./server.py /deploy/
COPY ./shipping_estimate_model.pkl /deploy/
WORKDIR /deploy/
RUN pip install -r requirements.txt
EXPOSE 80
CMD ["uvicorn","server:app","--host", "0.0.0.0", "--port", "80"]